# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2adc53269b8fd5ffb0ec884ba7a4e8bccc4771bb0449974816d3ab7a85eee3a76a08152462894d01cbbff79fad944569323d7b0d4ed79e23888b2948f65f47ca

test:
  secret_key_base: d6de51303e09dc2001cc7f52fb54cf8dd241133487e6ef694fca71951713a6786f40980bbe617994ef5583604c9921c8ecf2b550ec9d9af60a81267edaa530c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
